# Copyright (c) 2012, Yahoo! Inc.  All rights reserved.
# See LICENSE for information on reuse

source :rubygems
gem "eventmachine"
gem "em-http-request"
gem "sinatra"
gem "thin"
gem "json"
gem "thin"
gem "async_sinatra"
gem "hashie"