#!/usr/bin/ruby

# fibonacci sequence is generated by adding the previous two terms.
# example: (first 10 terms will be 1,2,3,5,8,13,21,34,55,89)

def fibonacci(sequence_upto_this_number)
  a,b = 0,1
  sequence_upto_this_number.times do
    (@sequence ||= [])
    puts a.to_s
     @sequence << a if !@sequence.include?(a)
    a,b = b,a+b
  end
end

def find_even_fibonacci
  
  @sequence.each{|s|
    (@total ||= 0)
    @total += s if (s % 2) == 0
  }
  
  puts @total.to_s
  
end

@cap = 4000000

# collect numbers
fibonacci(34)
puts "collect only the evens"
find_even_fibonacci


# store each fibonnaci sequence into an ARRAY, iterate through array after, adding only even numbers into the @total
# return and we are golden